# ─── SonarCloud Project Configuration - nRF7002 ─────────────────────────────

# Organisation and project details
sonar.organization=patilprathmesh08
sonar.projectKey=patilprathmesh08_nRFTest-Testing
sonar.projectName=CNR-Joyastic-nRF7002
sonar.projectVersion=1.0

# Source code location - only scan your own code
sonar.sources=src
sonar.inclusions=**/*.c,**/*.h

# Language
sonar.language=c
sonar.c.file.suffixes=.c
sonar.h.file.suffixes=.h

# Encoding
sonar.sourceEncoding=UTF-8

# Exclude build output and third party folders
sonar.exclusions=**/build/**,**/boards/**,**/child_image/**,**/sysbuild/**
